import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../home_controller.dart';
import 'power_chart.dart';

class PowerView extends StatelessWidget {
  PowerView({super.key});

  final HomeController ctr = Get.put(HomeController());

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(4.0),
      child: Container(
        padding: const EdgeInsets.all(18),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(22),
          boxShadow: [
            BoxShadow(
              color: Colors.black12,
              blurRadius: 8,
              offset: Offset(0, 3),
            ),
          ],
        ),
        child: GetBuilder<HomeController>(
          builder: (_) {
            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  "Electricity generated by solar",
                  style: TextStyle(
                    fontSize: 16,
                    color: Colors.grey,
                    fontWeight: FontWeight.w500,
                  ),
                ),
                const SizedBox(height: 6),
                Text(
                  "${ctr.totalKwh.toStringAsFixed(2)}KWh",
                  style: const TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 5),
                Row(
                  children: [
                    Container(
                      width: 12,
                      height: 12,
                      decoration: const BoxDecoration(
                        color: Colors.green,
                        shape: BoxShape.circle,
                      ),
                    ),
                    const SizedBox(width: 6),
                    const Text("Live"),
                    const Spacer(),
                    Icon(Icons.more_horiz, color: Colors.grey.shade600),
                  ],
                ),
                const SizedBox(height: 20),
                PowerChart(data: ctr.chartData),
              ],
            );
          },
        ),
      ),
    );
  }
}
